
package com.cisco.axl.api._10;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * All responses must extend abstractResponse.
 * 
 * <p>Java class for APIResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="APIResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APIResponse")
@XmlSeeAlso({
    ListTodAccessRes.class,
    ListSafSecurityProfileRes.class,
    GetCiscoCatalyst6000T1VoIPGatewayPriRes.class,
    GetRouteListRes.class,
    ListHuntPilotRes.class,
    ListSafForwarderRes.class,
    ListVpnProfileRes.class,
    GetPhysicalLocationRes.class,
    ListWifiHotspotRes.class,
    ListResourcePriorityNamespaceListRes.class,
    ListSdpTransparencyProfileRes.class,
    GetResourcePriorityNamespaceListRes.class,
    ListProcessNodeServiceRes.class,
    ListCiscoCatalyst6000T1VoIPGatewayPriRes.class,
    GetCtiRoutePointRes.class,
    GetCiscoCatalyst6000E1VoIPGatewayRes.class,
    ListRoutePlanRes.class,
    GetImeExclusionNumberGroupRes.class,
    ListImeServerRes.class,
    ListCCAProfilesRes.class,
    ListEndUserCapfProfileRes.class,
    GetImeRouteFilterElementRes.class,
    ListH323TrunkRes.class,
    ListUserRes.class,
    GetImeEnrolledPatternGroupRes.class,
    GetWifiHotspotRes.class,
    ListAppUserRes.class,
    GetEnterprisePhoneConfigRes.class,
    ListDeviceProfileRes.class,
    ExecuteSQLUpdateRes.class,
    ListApplicationServerRes.class,
    GetNetworkAccessProfileRes.class,
    GetGatekeeperRes.class,
    GetUserRes.class,
    ListGeoLocationFilterRes.class,
    ListDirectedCallParkRes.class,
    GetPhoneRes.class,
    GetCiscoCatalyst6000T1VoIPGatewayT1Res.class,
    ListLocalRouteGroupRes.class,
    ListUniversalDeviceTemplateRes.class,
    ListConferenceBridgeRes.class,
    ListProcessNodeRes.class,
    GetAudioCodecPreferenceListRes.class,
    ListImeRouteFilterGroupRes.class,
    ListRemoteDestinationRes.class,
    AddSNMPCommunityStringRes.class,
    UpdateSyslogConfigurationRes.class,
    ListIpPhoneServicesRes.class,
    ListRemoteDestinationProfileRes.class,
    GetEnterpriseFeatureAccessConfigurationRes.class,
    RemoveSNMPUserRes.class,
    ListAssignedPresenceServersRes.class,
    GetImeE164TransformationRes.class,
    GetSipRoutePatternRes.class,
    GetDeviceProfileOptionsRes.class,
    ListSipTrunkSecurityProfileRes.class,
    ListCiscoCatalyst600024PortFXSGatewayRes.class,
    GetProcessNodeServiceRes.class,
    GetAppUserRes.class,
    RemoveSNMPCommunityStringRes.class,
    ListLdapDirectoryRes.class,
    GetTranscoderRes.class,
    ListGeoLocationPolicyRes.class,
    GetCallingPartyTransformationPatternRes.class,
    GetHandoffConfigurationRes.class,
    ListSipRoutePatternRes.class,
    ListExternalCallControlProfileRes.class,
    GetImeFirewallRes.class,
    ListImeExclusionNumberRes.class,
    GetAnnunciatorRes.class,
    GetSafForwarderRes.class,
    ListSafCcdPurgeBlockLearnedRoutesRes.class,
    GetVg224Res.class,
    ListRemoteClusterRes.class,
    ListCalledPartyTransformationPatternRes.class,
    GetCcdHostedDNGroupRes.class,
    ListCommonDeviceConfigRes.class,
    GetUserProfileProvisionRes.class,
    ListSipDialRulesRes.class,
    ListCumaServerSecurityProfileRes.class,
    ListCtiRoutePointRes.class,
    ListLocationRes.class,
    ListSipRealmRes.class,
    GetIvrUserLocaleRes.class,
    GetLdapFilterRes.class,
    GetCredentialPolicyDefaultRes.class,
    GetRemoteDestinationProfileRes.class,
    ListMohAudioSourceRes.class,
    GetDeviceMobilityGroupRes.class,
    GetAarGroupRes.class,
    GetGatewayEndpointDigitalAccessPriRes.class,
    GetSipProfileRes.class,
    GetWLANProfileRes.class,
    GetSIPNormalizationScriptRes.class,
    ListDevicePoolRes.class,
    GetUniversalDeviceTemplateRes.class,
    GetSoftKeyTemplateRes.class,
    GetAnnouncementRes.class,
    GetSipTrunkSecurityProfileRes.class,
    GetRoutePartitionRes.class,
    ListApplicationUserCapfProfileRes.class,
    GetCCMVersionRes.class,
    GetAppServerInfoRes.class,
    GetSafCcdPurgeBlockLearnedRoutesRes.class,
    GetSNMPUserRes.class,
    GetSrstRes.class,
    ExecuteSQLQueryRes.class,
    ListCredentialPolicyRes.class,
    GetProcessNodeRes.class,
    GetPhoneButtonTemplateRes.class,
    GetCommonDeviceConfigRes.class,
    ListLdapFilterRes.class,
    GetPhoneSecurityProfileRes.class,
    ListVohServerRes.class,
    GetDirectedCallParkRes.class,
    ListIvrUserLocaleRes.class,
    ListChangeRes.class,
    ListImeExclusionNumberGroupRes.class,
    GetSoftKeySetRes.class,
    GetRecordingProfileRes.class,
    GetSNMPCommunityStringRes.class,
    ListNetworkAccessProfileRes.class,
    GetLineRes.class,
    ListVoiceMailPilotRes.class,
    DoAuthenticateUserRes.class,
    ListH323PhoneRes.class,
    ListPresenceRedundancyGroupRes.class,
    GetRegionRes.class,
    ListWlanProfileGroupRes.class,
    GetServiceParameterRes.class,
    ListDefaultDeviceProfileRes.class,
    GetVpnGatewayRes.class,
    GetIlsConfigRes.class,
    GetCcdAdvertisingServiceRes.class,
    GetApplicationUserCapfProfileRes.class,
    ListMeetMeRes.class,
    ListFeatureControlPolicyRes.class,
    ListImeClientRes.class,
    GetRoutePatternRes.class,
    GetImeEnrolledPatternRes.class,
    ListAnnunciatorRes.class,
    GetFeatureControlPolicyRes.class,
    ListRecordingProfileRes.class,
    GetEmccFeatureConfigRes.class,
    GetDevicePoolRes.class,
    GetCallPickupGroupRes.class,
    GetLbmGroupRes.class,
    GetLdapDirectoryRes.class,
    GetImeFeatureConfigRes.class,
    GetUcServiceRes.class,
    ListCalledPartyTracingRes.class,
    ListCallManagerGroupRes.class,
    ListMobileSmartClientProfileRes.class,
    ListPhoneSecurityProfileRes.class,
    GetMtpRes.class,
    ListTransPatternRes.class,
    GetSdpTransparencyProfileRes.class,
    ListDeviceMobilityGroupRes.class,
    GetCalledPartyTransformationPatternRes.class,
    ListImeEnrolledPatternGroupRes.class,
    ListMediaResourceGroupRes.class,
    GetFixedMohAudioSourceRes.class,
    ListMessageWaitingRes.class,
    ListVpnGroupRes.class,
    ListTransformationProfileRes.class,
    ListCallManagerRes.class,
    ListLdapSyncCustomFieldRes.class,
    GetGatewayEndpointAnalogAccessRes.class,
    GetMohServerRes.class,
    GetMlppDomainRes.class,
    ListPhoneRes.class,
    ListLineRes.class,
    ListEnterpriseFeatureAccessConfigurationRes.class,
    GetCcdHostedDNRes.class,
    ListDirNumberAliasLookupandSyncRes.class,
    ListImeEnrolledPatternRes.class,
    DoUpdateRemoteClusterRes.class,
    GetImeRouteFilterGroupRes.class,
    ListSrstRes.class,
    GetTransPatternOptionsRes.class,
    GetSyslogConfigurationRes.class,
    GetPhoneNtpRes.class,
    ListRegionRes.class,
    ListPhysicalLocationRes.class,
    ListCallPickupGroupRes.class,
    GetInterClusterServiceProfileRes.class,
    GetH323GatewayRes.class,
    ListCcdAdvertisingServiceRes.class,
    ListImeFirewallRes.class,
    GetGatewayEndpointDigitalAccessT1Res.class,
    ListRoutePartitionRes.class,
    GetLocalRouteGroupRes.class,
    GetDirectoryLookupDialRulesRes.class,
    ListUnassignedPresenceUsersRes.class,
    ListUserProfileProvisionRes.class,
    ListVoiceMailProfileRes.class,
    ListApplicationDialRulesRes.class,
    GetHuntListRes.class,
    UpdateSNMPCommunityStringRes.class,
    GetH323TrunkRes.class,
    ListAdvertisedPatternsRes.class,
    GetFacInfoRes.class,
    GetH323PhoneRes.class,
    ListUserGroupRes.class,
    GetCommonPhoneConfigRes.class,
    GetMobilityRes.class,
    GetImeClientRes.class,
    ListGeoLocationRes.class,
    ListDialPlanRes.class,
    AddSNMPUserRes.class,
    GetResourcePriorityNamespaceRes.class,
    ListCallingPartyTransformationPatternRes.class,
    ListAudioCodecPreferenceListRes.class,
    GetGeoLocationPolicyRes.class,
    ListGatewayRes.class,
    GetVoiceMailPortRes.class,
    ListVpnGatewayRes.class,
    GetUniversalLineTemplateRes.class,
    GetIpPhoneServicesRes.class,
    GetConferenceBridgeRes.class,
    ListPresenceGroupRes.class,
    GetServiceProfileRes.class,
    GetGeoLocationRes.class,
    GetCallerFilterListRes.class,
    GetImportedDirectoryUriCatalogsRes.class,
    GetMessageWaitingRes.class,
    ListUcServiceRes.class,
    GetDateTimeGroupRes.class,
    GetLocationRes.class,
    GetTvsCertificateRes.class,
    GetFallbackFeatureConfigRes.class,
    GetGatewayEndpointDigitalAccessBriRes.class,
    ListBillingServerRes.class,
    GetImeLearnedRoutesRes.class,
    GetLdapAuthenticationRes.class,
    ListDialPlanTagRes.class,
    ListVoiceMailPortRes.class,
    ListRoutePatternRes.class,
    ListTimePeriodRes.class,
    GetDirNumberAliasLookupandSyncRes.class,
    GetBillingServerRes.class,
    GetFeatureGroupTemplateRes.class,
    ListCallParkRes.class,
    GetSipProfileOptionsRes.class,
    GetBlockedLearnedPatternsRes.class,
    GetRemoteClusterRes.class,
    ListMlppDomainRes.class,
    ListFallbackProfileRes.class,
    ListHuntListRes.class,
    GetPhoneOptionsRes.class,
    ListLineGroupRes.class,
    GetMediaResourceListRes.class,
    GetMohAudioSourceRes.class,
    GetAdvertisedPatternsRes.class,
    ListBlockedLearnedPatternsRes.class,
    GetSipDialRulesRes.class,
    ListDhcpSubnetRes.class,
    GetExternalCallControlProfileRes.class,
    ListDeviceMobilityRes.class,
    GetVoiceMailProfileRes.class,
    GetGatewayRes.class,
    ListMobilityProfileRes.class,
    UpdateSNMPMIB2ListRes.class,
    GetTransPatternRes.class,
    GetRouteFilterRes.class,
    GetLbmHubGroupRes.class,
    ListAnnouncementRes.class,
    ListImeE164TransformationRes.class,
    ListRouteFilterRes.class,
    GetPresenceGroupRes.class,
    ListCssRes.class,
    ListServiceProfileRes.class,
    GetLineGroupRes.class,
    GetCredentialPolicyRes.class,
    GetTransformationProfileRes.class,
    GetImeServerRes.class,
    ListPhoneNtpRes.class,
    ListResourcePriorityNamespaceRes.class,
    GetImeExclusionNumberRes.class,
    ListUniversalLineTemplateRes.class,
    GetMobilityProfileRes.class,
    GetLdapSyncCustomFieldRes.class,
    ListCustomUserFieldRes.class,
    UpdateCcdFeatureConfigRes.class,
    GetLicensedUserRes.class,
    ListFeatureGroupTemplateRes.class,
    GetMediaResourceGroupRes.class,
    GetLineOptionsRes.class,
    GetCallParkRes.class,
    ListCommonPhoneConfigRes.class,
    ListGatekeeperRes.class,
    GetPresenceRedundancyGroupRes.class,
    GetPhoneTypeDisplayInstanceRes.class,
    GetCustomUserFieldRes.class,
    ListMediaResourceListRes.class,
    GetLdapSystemRes.class,
    GetDhcpServerRes.class,
    ListH323GatewayRes.class,
    ListCiscoCatalyst6000T1VoIPGatewayT1Res.class,
    GetVohServerRes.class,
    GetTimeScheduleRes.class,
    ListRouteListRes.class,
    ListAssignedPresenceUsersRes.class,
    ListDateTimeGroupRes.class,
    GetMeetMeRes.class,
    GetCallManagerRes.class,
    ListCmcInfoRes.class,
    ListDdiRes.class,
    GetTimePeriodRes.class,
    ListSIPNormalizationScriptRes.class,
    GetUserGroupRes.class,
    GetApplicationDialRulesRes.class,
    ListRouteGroupRes.class,
    GetCcdRequestingServiceRes.class,
    GetRemoteDestinationRes.class,
    GetFallbackProfileRes.class,
    GetWlanProfileGroupRes.class,
    GetOSVersionRes.class,
    GetApplicationServerRes.class,
    ListServiceParameterRes.class,
    GetVoiceMailPilotRes.class,
    GetPageLayoutPreferencesRes.class,
    GetCumaServerSecurityProfileRes.class,
    GetEndUserCapfProfileRes.class,
    ListFacInfoRes.class,
    ListLbmHubGroupRes.class,
    ListSoftKeyTemplateRes.class,
    ListTimeScheduleRes.class,
    ListImportedDirectoryUriCatalogsRes.class,
    ListImeRouteFilterElementRes.class,
    GetSipRealmRes.class,
    ListAarGroupRes.class,
    ListDhcpServerRes.class,
    ListCiscoCatalyst6000E1VoIPGatewayRes.class,
    ListCallerFilterListRes.class,
    GetVpnGroupRes.class,
    GetGatewaySccpEndpointsRes.class,
    ListMtpRes.class,
    ListMohServerRes.class,
    GetCssRes.class,
    ListCcdHostedDNGroupRes.class,
    ListTvsCertificateRes.class,
    GetSNMPMIB2ListRes.class,
    GetHuntPilotRes.class,
    GetCcdFeatureConfigRes.class,
    GetSipTrunkRes.class,
    GetDialPlanRes.class,
    GetTodAccessRes.class,
    GetSafSecurityProfileRes.class,
    GetGeoLocationFilterRes.class,
    GetDefaultDeviceProfileRes.class,
    GetCallManagerGroupRes.class,
    ListUnassignedPresenceServersRes.class,
    GetMobileVoiceAccessRes.class,
    ListWLANProfileRes.class,
    ListCcdHostedDNRes.class,
    ListSipTrunkRes.class,
    GetRouteGroupRes.class,
    ListSipProfileRes.class,
    UpdateSNMPUserRes.class,
    ListPhoneButtonTemplateRes.class,
    GetDialPlanTagRes.class,
    ListLbmGroupRes.class,
    GetCmcInfoRes.class,
    GetDdiRes.class,
    GetDeviceMobilityRes.class,
    ListDirectoryLookupDialRulesRes.class,
    GetCiscoCatalyst600024PortFXSGatewayRes.class,
    GetVpnProfileRes.class,
    ListTranscoderRes.class,
    GetDeviceProfileRes.class,
    StandardResponse.class,
    GetCCAProfilesRes.class,
    GetMobileSmartClientProfileRes.class,
    GetDhcpSubnetRes.class,
    GetNumDevicesRes.class
})
public abstract class APIResponse {

    @XmlAttribute
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger sequence;

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

}
